# Generated by Django 3.1.2 on 2020-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0002_game_level_of_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
