# Generated by Django 3.1.2 on 2020-10-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0006_game_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='level_of_difficulty',
            field=models.IntegerField(choices=[('Easy', 0), ('Medium', 1), ('Hard', 2)]),
        ),
    ]
